import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalFooter from "../components/ConditionalFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The root layout is a server component.  We conditionally render
// the navbar using a separate client component so that we can call
// `usePathname` safely.
import ConditionalNavbar from "../components/ConditionalNavbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* navbar will be omitted on auth/portal pages via client component */}
        <ConditionalNavbar />
        {children}
        {/* footer also hidden on auth/portal pages */}
        <ConditionalFooter />
      </body>
    </html>
  );
}
